"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ChartIcon } from "@/components/icons";
import { saveSession, saveBridgeToken } from "@/lib/auth";

export default function LoginPage() {
  const router = useRouter();
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("admin");
  const [bridgeToken, setBridgeToken] = useState("DEMO-1234");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);
    try {
      const res = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Login failed");
      saveSession(data.token);
      saveBridgeToken(bridgeToken.trim() || "DEMO-1234");
      router.replace("/");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Login failed");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="flex min-h-screen flex-col justify-center px-6">
      <div className="mb-8 text-center">
        <div className="mx-auto mb-3 grid h-14 w-14 place-items-center rounded-2xl bg-accent/10 text-accent">
          <ChartIcon className="h-8 w-8" />
        </div>
        <h1 className="text-2xl font-bold text-accent">AI Trading Bot</h1>
        <p className="mt-1 text-sm text-muted">
          Sign in to your real-time dashboard
        </p>
      </div>

      <form onSubmit={onSubmit} className="space-y-4">
        <Field label="Username">
          <input
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="input"
            autoComplete="username"
          />
        </Field>
        <Field label="Password">
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="input"
            autoComplete="current-password"
          />
        </Field>
        <Field
          label="Bridge Connection Token"
          hint="Generated by your local bridge. Use DEMO-1234 to preview with simulated data."
        >
          <input
            value={bridgeToken}
            onChange={(e) => setBridgeToken(e.target.value)}
            className="input font-mono"
          />
        </Field>

        {error && <p className="text-sm text-loss">{error}</p>}

        <button
          type="submit"
          disabled={loading}
          className="w-full rounded-xl bg-accent py-3 text-sm font-bold text-black transition hover:bg-accent-soft disabled:opacity-60"
        >
          {loading ? "Signing in…" : "Sign In"}
        </button>
      </form>

      <p className="mt-6 text-center text-xs text-muted">
        Default demo login: <span className="text-white">admin / admin</span>
      </p>

      <style jsx>{`
        :global(.input) {
          width: 100%;
          border-radius: 0.75rem;
          border: 1px solid rgba(255, 255, 255, 0.08);
          background: #121a18;
          padding: 0.75rem 0.9rem;
          font-size: 0.95rem;
          color: #e6f0ec;
          outline: none;
        }
        :global(.input:focus) {
          border-color: rgba(34, 197, 94, 0.5);
        }
      `}</style>
    </div>
  );
}

function Field({
  label,
  hint,
  children,
}: {
  label: string;
  hint?: string;
  children: React.ReactNode;
}) {
  return (
    <label className="block">
      <span className="mb-1.5 block text-[13px] font-medium text-muted">
        {label}
      </span>
      {children}
      {hint && <span className="mt-1 block text-[11px] text-muted/70">{hint}</span>}
    </label>
  );
}
